### ISSUE TITLE
[BUG] Errors Running Headless on Ubuntu Server

### ISSUE THREAD

**Issue by birwin88** [joshuar/go-hass-agent#55]
**Describe the bug**
When trying to run on a headless ubuntu server, I got the following errors it seems to fail to run due to a lack of a display environment.

     PlatformError: X11: The DISPLAY environment variable is missing
     panic: NotInitialized: The GLFW library is not initialized

**To Reproduce**
1. Installed the 64bit deb package on ubuntu 23.04.
     `sudo dpkg -i go-hass-agent_5.1.2-1_amd64.deb`
2. Attempt to run the following command: 
    `go-hass-agent register --token LONGLIVEACCESSTOKEN --server https://myserver.domain.com`

**Expected behavior**
Expected this to register with home assistant and then run as service reporting details to home assistant that I could display in a dashboard.  

**Logs**

```
7:46AM DBG Debug logging enabled.
7:46AM DBG Setting language to [en-US].
7:46AM DBG Running UpgradeConfig.
7:46AM DBG Registration status is false
7:46AM DBG Running ValidateConfig.
7:46AM INF Registration required. Starting registration process.
2023/11/22 07:46:04 PlatformError: X11: The DISPLAY environment variable is missing
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0xc00031f768?})
        /home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20231102141658-eca20e8abded/error.go:173 +0x1ae
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        /home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20231102141658-eca20e8abded/error.go:184
github.com/go-gl/glfw/v3.3/glfw.CreateStandardCursor(0xebf5c0?)
        /home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20231102141658-eca20e8abded/input.go:512 +0x45
fyne.io/fyne/v2/internal/driver/glfw.initCursors()
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/internal/driver/glfw/window_desktop.go:49 +0x5f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW.func1()
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/internal/driver/glfw/loop_desktop.go:22 +0x54
sync.(*Once).doSlow(0xc00031f878?, 0x4484e5?)
        /opt/hostedtoolcache/go/1.20.10/x64/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.20.10/x64/src/sync/once.go:65
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW(0x7f791bdb4d28?)
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/internal/driver/glfw/loop_desktop.go:15 +0x45
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1()
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/internal/driver/glfw/window.go:954 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0xc000486180)
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/internal/driver/glfw/loop.go:53 +0x110
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow(0xc00022df10, {0xfe787e, 0xe}, 0x1)
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/internal/driver/glfw/window.go:953 +0xd8
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).CreateWindow(...)
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/internal/driver/glfw/window.go:945
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).SetSystemTrayMenu.func1()
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/internal/driver/glfw/driver_desktop.go:56 +0xd4
sync.(*Once).doSlow(0x43291d?, 0xedefc0?)
        /opt/hostedtoolcache/go/1.20.10/x64/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.20.10/x64/src/sync/once.go:65
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).SetSystemTrayMenu(0xc00022df10?, 0xc000486150?)
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/internal/driver/glfw/driver_desktop.go:39 +0x5f
fyne.io/fyne/v2/app.(*fyneApp).SetSystemTrayMenu(0x43cc30?, 0xe80ae0?)
        /home/runner/go/pkg/mod/fyne.io/fyne/v2@v2.4.1/app/app_xdg.go:143 +0x42
github.com/joshuar/go-hass-agent/internal/agent/ui/fyneUI.(*fyneUI).DisplayTrayIcon(0xc000013878, {0x118f160, 0xc000423d80})
        /home/runner/work/go-hass-agent/go-hass-agent/internal/agent/ui/fyneUI/fyneUI.go:135 +0x9db
github.com/joshuar/go-hass-agent/internal/agent.Register({{0x1001c33, 0x20}, 0x0, 0x0}, {0x7ffc271f6659, 0x1f}, {0x7ffc271f6598, 0xb7})
        /home/runner/work/go-hass-agent/go-hass-agent/internal/agent/agent.go:161 +0x22d
github.com/joshuar/go-hass-agent/cmd.glob..func2(0x17abb20?, {0xfd2d44?, 0x5?, 0x5?})
        /home/runner/work/go-hass-agent/go-hass-agent/cmd/register.go:25 +0x51
github.com/spf13/cobra.(*Command).execute(0x17abb20, {0xc00044e8c0, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x17abe00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/joshuar/go-hass-agent/cmd.Execute()
        /home/runner/work/go-hass-agent/go-hass-agent/cmd/root.go:51 +0x25
main.main()
        /home/runner/work/go-hass-agent/go-hass-agent/main.go:29 +0x17
````

**Comment by joshuar** [comment]
Hey @birwin88, it looks like you aren't adding the `--terminal` option, which explicitly sets the agent in no-graphical mode and where it won't try to initialise any graphical libraries at all. Can you try adding that:

```shell
go-hass-agent register --terminal --token LONGLIVEACCESSTOKEN --server https://myserver.domain.com
```
You'll also need to specify it when running the agent after registration.

I'm now just thinking why do I even have this option, because I can likely auto-detect when there is a graphical session early in the code and autoload the graphical stuff or not. The flag can then be used to **explicitly** disable the graphical stuff. Maybe that is the better way.

**Comment by joshuar** [comment]
Hey @birwin88, [v6.0.1](https://github.com/joshuar/go-hass-agent/compare/v6.0.0...v6.0.1) has been released which should fix this issue by auto-detecting whether a GUI can be used. Can you give it a try when you get a chance and report back?

**Comment by birwin88** [comment]
Tested it today and it works great.  Thanks!

**Comment by joshuar** [comment]
Great! I'll close this off.
